---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.module"
exclude_paths:
- node_modules/**/*
- _site/**/*
- spec/**/*
- app/tmp/**/*
- app/experiments/tmp/**/*
- app/experiments/dist/**/*
- experiments/**/*
- .idea/**/*
- node_modules/**/*
- bower_components/**/*
- vendor/**/*
