sudo: false
language: ruby

rvm:
  - 2.6.3

before_install:
  - nvm install 14.15.3
  - nvm use 14.15.3

  - npm install --global gulp-cli
  - npm install

script:
  - npm run lint
  - npm run test --coverage
  - npm run fomantic
  - npm run build

  - cd docs && bundle exec jekyll build

# Currently sing default github pages deployment, so this Travis build is only for testing purposes
# All assets generated above should be committed to repo
#deploy:
#  skip_cleanup: true
