sudo: false
language: ruby

rvm:
  - 2.1

before_install:
  - nvm install 6.9.2
  - nvm use 6.9.2
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add grunt-cli
  - yarn global add gulp-cli

script:
  - bundle install
  - bundle exec jekyll build

  - yarn install
  - yarn run semantic-ui
  - grunt build
