sudo: false
language: ruby

rvm:
  - 2.1

before_install:
  - nvm install 6.9.2
  - nvm use 6.9.2

  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add grunt-cli
  - yarn global add gulp-cli
  - yarn global add bower

script:
  - yarn install
  - bower install
  - yarn run semantic-ui
  - grunt build

  - bundle exec jekyll build

# Currently sing default github pages deployment, so this Travis build is only for testing purposes
# All assets generated above should be commited to repo
#deploy:
#  skip_cleanup: true
