exclude: ["bower_components", "node_modules", "bower.json", "Gemfile*", "Gruntfile.js", "package.json", "app"]
paginate: 5
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
            defaultjs: "defaultjs.html"
            defaultcss: "defaultcss.html"
            googletag: "googletag.html"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"