exclude: [
    "bower_components",
    "node_modules",
    "bower.json",
    "Gemfile*",
    "package.json",
    "package-lock.json",
    "babel.config.js",
    "gulpfile.js",
    "app",
    "script",
    "app/*",
    "tmp",
    "vendor",
    "README.md",
    "semantic.json",
    "webpack.config.js",
    "tinify.js",
    "alagodich.sublime-project",
    "alagodich.sublime-workspace",
    "/semantic/",
    "irealb_parser.js",
    "yarn.lock",
    "webpack.config.*"
]
plugins: ["jekyll-paginate", "jekyll-sitemap"]
paginate: 5
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
            googletag: "googletag.html"
            description: "My personal blog"
            keywords: "travel, programming, music"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
compress_html:
    clippings: all
    comments:  ["<!-- ", " -->"]
    endings:   all
