exclude: ["bower_components", "node_modules", "bower.json", "Gemfile*", "Gruntfile.js", "package.json", "app", "README.md"]
paginate: 5
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
            defaultcss: "defaultcss.html"
            defaultmodules: "defaultmodules.html"
            app: "app.html"
            googletag: "googletag.html"
            description: "My personal blog"
            keywords: "travel, programming, music"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"