exclude: []
source: "docs"
plugins: ["jekyll-paginate", "jekyll-sitemap"]
paginate: 5
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
            googletag: "googletag.html"
            description: "My personal blog"
            keywords: "travel, programming, music"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
compress_html:
    clippings: all
    comments:  ["<!-- ", " -->"]
    endings:   all
